# -*- coding: utf-8 -*-
"""git_intro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xsS2GHxDXpOYrnTCkxKxKHbi2JJ_u89H
"""

a = 1
b = 2

x = a + b
x

